### PR TITLE
fix: clean props sent to children

### LINKED ISSUE #27: React 15.3.0 support
React 15.3.0 introduced new warnings https://facebook.github.io/react/warnings/unknown-prop.html 
Opening the ticket to discuss and solve them.

### PR DESCRIPTION
**Pull request by mikaoelitiana**
remove proprietary props so they are not sent to children because this
causes a warning.

fixes #27

### CODE REVIEW

File: src/prop_types.js [hunk 1]
```diff
@@ -150,3 +150,20 @@ const layoutDangerousStyles = everythingDangerousStyles;
...
+export const cleanProps = function (props) {
+  const proprietaryProps = Object.keys(Object.assign({},
+    HLayoutPropTypes,
+    HLayoutDefaultPropTypes,
+    HLayoutItemPropTypes,
+    VLayoutPropTypes,
+    VLayoutDefaultPropTypes,
+    VLayoutItemPropTypes
+  ));
+  let safeProps = Object.assign({}, props);
```
Comment (bywo) [inline src/prop_types.js]: we have `lodash` as a dependency, so you can use `_.omit`

File: src/prop_types.js [hunk 2]
```diff
@@ -150,3 +150,20 @@ const layoutDangerousStyles = everythingDangerousStyles;
 const layoutItemDangerousStyles = everythingDangerousStyles.concat([
   "position", "margin", "marginTop", "marginBottom", "marginLeft", "marginRight"
 ]);
+
+
+export const cleanProps = function (props) {
+  const proprietaryProps = Object.keys(Object.assign({},
```
Comment (bywo) [inline src/prop_types.js]: can calculate this once outside of the function body to save some computation

**Comment by bywo** [comment]
thanks for taking this on! just a couple comments.

File: src/prop_types.js (hunk 1 above)
Comment (mikaoelitiana) [reply src/prop_types.js]: Alright I will do so. I wasn't sure because I saw a ticket or something about removing lodash but I prefer to use it in fact

File: src/prop_types.js (hunk 2 above)
Comment (mikaoelitiana) [reply src/prop_types.js]: Yes good idea

**Comment by mikaoelitiana** [comment]
I have updated the code to use lodash.

**Comment by bywo** [comment]
awesome, thank you!

**Comment by bywo** [comment]
published `1.2.4` with these changes
